# 1. Numpy 시작하기

### Remind : 리스트

In [2]:
arr = [1, "two", 3.0]

print(arr)

[1, 'two', 3.0]


list는 연산이 매우 느리다.
수치연산을 전문적으로 하는 라이브러리가 numpy다.

### numpy 모듈 불러오기

In [3]:
import numpy as np

### 왜 numpy를 사용해야 할까?

#### List

In [4]:
L = range(1000)

# timeit은 작은 코드 세그먼트의 실행 속도를 재준다.
# %는 notebook환경에서의 magic keyword이다. 
# 모듈 이름에 %를 붙이게 되면 노트북 환경에서 뭔가를 하겠다는 특수한 시그널이 된다.
%timeit [i**2 for i in L] 

415 µs ± 8.62 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


#### numpy.array

In [5]:
N = np.arange(1000)

%timeit N**2

1.72 µs ± 33.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


numpy가 loop 수도 많은데 시간도 훨씬 적다. -> numpy를 사용해야 하는 이유

### numpy.array
  
  numpy의 Container, array

(여러 자료를 담을 수 있는 자료형 = Container)

In [6]:
arr = np.array([1,2,3])

arr

array([1, 2, 3])

In [7]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr.shape

(3,)

In [9]:
arr_2d.shape

(3, 3)

### Numpy로 연산하기

### Vector와 Scalar 사이의 연산

벡터의 각 원소에 대해서 연산을 진행

In [10]:
x = np.array([1,2,3])
c = 5

# format함수 : 브리켓을 열고 닫으면, 열고 닫은 곳에 함수의 인자를 채워주는 역할
print("더하기: {}".format(x+c))
print("빼기: {}".format(x-c))
print("곱하기: {}".format(x*c))
print("나누기: {}".format(x/c))

더하기: [6 7 8]
빼기: [-4 -3 -2]
곱하기: [ 5 10 15]
나누기: [0.2 0.4 0.6]


### Vector와 Vector사이의 연산

벡터와 **같은 인덱스**끼리 연산이 진행!!

In [12]:
# array의 인자는 반드시 하나! 주의할 것.
y = np.array([1,3,5])

z = np.array([2,9,20])

print("더하기: {}".format(y+z))
print("빼기: {}".format(y-z))
print("곱하기: {}".format(y*z))
print("나누기: {}".format(y/z))

더하기: [ 3 12 25]
빼기: [ -1  -6 -15]
곱하기: [  2  27 100]
나누기: [0.5        0.33333333 0.25      ]


## Array Indexing

Python의 리스트와 유사하게 진행

In [13]:
# 2차원일 경우 : [(row), (column)]

W = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

W[0,0]

1

In [14]:
W[2,3]

12

In [15]:
W

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

2,3 -> 행 : 인덱스 0~1 -> [0:2]  
6,7 -> 열 : 인덱스 1~2 -> [1,3]

In [16]:
W[0:2, 1:3]

array([[2, 3],
       [6, 7]])

#### Indexing에서의 생략

[a:b]

[:b] - 맨 처음부터 b까지 (~b-1)  
[a:] - a부터 끝까지  
[:]  - 처음부터 끝까지  

In [17]:
W[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
W[0:2,0:4]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
W[0:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
W[0:3,2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [21]:
W[:,2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

## Array의 Broadcasting
Numpy가 연산을 진행하는 특수한 방법  
  
1. _M×N, M×1_ M×N 행렬, 하나의 열 벡터  
   연산에 대응하는 원소들이 없을 때, 하나의 열을 복사해서 elementwise하게 계산해준다.  
  
1. _M×N, 1×N_ M×N 행렬, 하나의 행 벡터  
   하나의 행을 복사해서 차원을 동일하게 맞춰준 후에 계산해준다.  
  
2. _M×1, 1×N_ 열 벡터와 행 벡터
   서로서로 부족한 것을 채워주는 쪽으로 브로드캐스팅 된다. 결과물은 M×N
   브로드캐스팅은 뒤쪽 차원부터 맞춰준다.  
  
  
> 기본적으로 같은 Type의 data에 대해서만 연산이 적용 가능  
> 하지만 만약에 피연산자가 연산 가능하도록 변환이 가능하다면 연산이 가능합니다.  
> 이를 Broadcasting이라고 합니다.

### 1. M by N, M by 1

In [23]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
x = np.array([0,1,0]) # 행벡터

# np.array는 기본적으로 행 벡터
# 전치를 시켜줘야 열 벡터

print(a+x)
print("---------------")
x = x[:,None] #전치를 시키는 한 방법
print(a+x)

[[1 3 3]
 [4 6 6]
 [7 9 9]]
---------------
[[1 2 3]
 [5 6 7]
 [7 8 9]]


### M by N, 1 by N

In [24]:
y = np.array([0,1,-1])

print(a*y)

[[ 0  2 -3]
 [ 0  5 -6]
 [ 0  8 -9]]


### M by 1, 1 by N

In [25]:
t = np.array([1,2,3]) # 열 벡터로 바꿔줘야 함!
t = t[:, None] # Transpose

u = np.array([2,0,-2])

print(t+u)

'''
1 1 1   2 0 -2
2 2 2 + 2 0 -2
3 3 3   2 0 -2
'''

[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]


'\n1 1 1   2 0 -2\n2 2 2 + 2 0 -2\n3 3 3   2 0 -2\n'

## Ⅲ. Numpy로 선형대수 지식 끼얹기

### A. basics

### 영벡터(영행렬)

-원소가 모두 0인 벡터(행렬)  
  
-`np.zeros(dim)`을 통해 생성 dim은 값, 혹은 튜플(, ) 형태로 차원 전달  

In [26]:
np.zeros(3)

array([0., 0., 0.])

In [27]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

### 일벡터(일행렬)
  
- 원소가 모두 1인 벡터(행렬)
- `np.ones(dim)`을 통해 생성, dim은 값, 튜플(, )

In [28]:
np.ones(2)

array([1., 1.])

In [29]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

영벡터와 일벡터는 자주 쓰이는 만큼 독립적인 메소드로 존재한다.

### 대각행렬(diagonal matrix)
  
- Main diagonal을 제외한 성분이 0인 행렬 
- `np.diag((main_diagonals))`을 통해 생성, 튜플 형태로 전달.

In [30]:
np.diag((2,4))

array([[2, 0],
       [0, 4]])

In [31]:
np.diag((1,3,5))

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

### 항등행렬(identity matrix)
  
- Main diagonal이 1인 대각행렬
- `np.eye(n, (dtype=int, uint,float, complex, ...))`를 사용

In [32]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [33]:
np.eye(2).dtype

dtype('float64')

In [34]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 행렬곱(dot product)
  
- 행렬간의 곱 연산
- `np.dot()` 첫번재 행렬의 모든 행벡터와 두번째 행렬의 모든 열벡터의 내적 연산 행렬
- `@` or `np.matmul()` 이게 보통의 행렬곱
- 3차원 이상의 행렬에서 `np.dot()`과 `@`(or `np.matmul()`)은 다르게 연산됨

In [36]:
mat_1 = np.array([[1,4],[2,3]])
mat_2 = np.array([[7,9],[0,6]])

mat_1.dot(mat_2)

array([[ 7, 33],
       [14, 36]])

In [37]:
mat_1 @ mat_2

array([[ 7, 33],
       [14, 36]])

In [38]:
mat_3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
mat_4 = np.array([[[0,1,2],[3,4,5],[6,7,8]],[[0,1,2],[3,4,5],[6,7,8]],[[0,1,2],[3,4,5],[6,7,8]]])

mat_3.dot(mat_4)

array([[[[ 24,  30,  36],
         [ 24,  30,  36],
         [ 24,  30,  36]],

        [[ 51,  66,  81],
         [ 51,  66,  81],
         [ 51,  66,  81]],

        [[ 78, 102, 126],
         [ 78, 102, 126],
         [ 78, 102, 126]]],


       [[[ 24,  30,  36],
         [ 24,  30,  36],
         [ 24,  30,  36]],

        [[ 51,  66,  81],
         [ 51,  66,  81],
         [ 51,  66,  81]],

        [[ 78, 102, 126],
         [ 78, 102, 126],
         [ 78, 102, 126]]],


       [[[ 24,  30,  36],
         [ 24,  30,  36],
         [ 24,  30,  36]],

        [[ 51,  66,  81],
         [ 51,  66,  81],
         [ 51,  66,  81]],

        [[ 78, 102, 126],
         [ 78, 102, 126],
         [ 78, 102, 126]]]])

In [39]:
mat_3@mat_4

array([[[ 24,  30,  36],
        [ 51,  66,  81],
        [ 78, 102, 126]],

       [[ 24,  30,  36],
        [ 51,  66,  81],
        [ 78, 102, 126]],

       [[ 24,  30,  36],
        [ 51,  66,  81],
        [ 78, 102, 126]]])

### B. Furthermore

### 트레이스(trace)
  
- Main diagonal의 합 
- `np.trace()`를 사용

In [40]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr.trace()

15

In [42]:
np.eye(2, dtype = int).trace()

2

### 행렬식(determinant)
  
- 행렬을 대표하는 값들 중 하나
- 선형변환에서 Vector의 Scaling 척도(어떤 행렬을 선형변환했을 때 얼마나 원 벡터가 변하는가)
- `np.linalg.det()`으로 계산  

In [43]:
arr_2 = np.array([[2,3],[1,6]])

arr_2

array([[2, 3],
       [1, 6]])

In [44]:
np.linalg.det(arr_2)

9.000000000000002

In [45]:
arr_3 = np.array([[1,4,7],[2,5,8],[3,6,9]])

arr_3

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [46]:
np.linalg.det(arr_3)

0.0

### 역행렬 (Inverse Matrix)
  
- 행렬 A에 대해 AB=BA=I를 만족하는 행렬 B = A^(-1)
- `np.linalg.inv()`으로 계산

In [47]:
mat = np.array([[1,4],[2,3]])

mat

array([[1, 4],
       [2, 3]])

In [48]:
mat_inv = np.linalg.inv(mat)

mat_inv

array([[-0.6,  0.8],
       [ 0.4, -0.2]])

In [49]:
mat@mat_inv

array([[1., 0.],
       [0., 1.]])

### 고유값과 고유벡터 (eigenvalue and eigenvector)
  
- 아이겐밸류, 아이겐벡터
- 정방행렬(N by N) A에 대해서 $Ax = \lambda x$와 이에 대응하는 벡터
- $(A-lambda I)x = 0$
- `np.linalg.eig()`으로 계산
- 각 인덱스마다 열벡터로 확인

In [50]:
mat = np.array([[2,0,-2],[1,1,-2],[0,0,1]])

mat

array([[ 2,  0, -2],
       [ 1,  1, -2],
       [ 0,  0,  1]])

In [51]:
np.linalg.eig(mat)

(array([1., 2., 1.]),
 array([[0.        , 0.70710678, 0.89442719],
        [1.        , 0.70710678, 0.        ],
        [0.        , 0.        , 0.4472136 ]]))

#### Validation

In [53]:
eig_val, eig_vec = np.linalg.eig(mat)

eig_val

array([1., 2., 1.])

In [54]:
mat @ eig_vec[:, 0] # Ax

array([0., 1., 0.])

In [55]:
eig_val[0] * eig_vec[:,0] #(lambda) x

array([0., 1., 0.])